import { writable } from 'svelte/store';

export const language = writable('it'); // 'it' per Italiano, 'en' per Inglese

export const cards = [
    { id: 1, name: { it: "Embrione", en: "Embryo" }, image: "/src/assets/trinity-tarot-card-01-embryo.jpg", description: { it: "L'inizio di un nuovo ciclo, la nascita di qualcosa di importante.", en: "The beginning of a new cycle, the birth of something important." }, meaning: { it: "Simbolo di potenzialità e crescita interiore.", en: "Symbol of potential and inner growth." }, oracle: { it: "Accogli il nuovo con apertura e curiosità.", en: "Embrace the new with openness and curiosity." } },
    { id: 2, name: { it: "Occhio", en: "Eye" }, image: "/src/assets/trinity-tarot-card-02-eye.jpg", description: { it: "Chiarezza e visione interiore, la capacità di vedere oltre l'apparenza.", en: "Clarity and inner vision, the ability to see beyond appearances." }, meaning: { it: "Invito a fidarsi della propria intuizione.", en: "A call to trust your intuition." }, oracle: { it: "Osserva con attenzione, la verità è davanti a te.", en: "Observe carefully, the truth is in front of you." } },
    { id: 3, name: { it: "Passo", en: "Step" }, image: "/src/assets/trinity-tarot-card-03-step.jpg", description: { it: "Ogni passo è importante nel cammino della vita, anche i più piccoli.", en: "Every step is important on life's journey, even the smallest ones." }, meaning: { it: "Simbolo di progressione e cambiamento graduale.", en: "Symbol of progression and gradual change." }, oracle: { it: "Avanza con fiducia, ogni passo conta.", en: "Move forward with confidence, every step matters." } },
    { id: 4, name: { it: "Mano", en: "Hand" }, image: "/src/assets/trinity-tarot-card-04-hand.jpg", description: { it: "L'azione e la creazione, la capacità di dare forma ai propri sogni.", en: "Action and creation, the ability to shape one's dreams." }, meaning: { it: "Simbolo di lavoro, manifestazione e dono.", en: "Symbol of work, manifestation, and giving." }, oracle: { it: "Dai forma alle tue idee con determinazione.", en: "Give shape to your ideas with determination." } },
    { id: 5, name: { it: "Bocca", en: "Mouth" }, image: "/src/assets/trinity-tarot-card-05-mouth.jpg", description: { it: "Comunicazione e espressione, il potere della parola.", en: "Communication and expression, the power of words." }, meaning: { it: "Simbolo della verità e dell'espressione autentica.", en: "Symbol of truth and authentic expression." }, oracle: { it: "Parla con sincerità, le parole hanno potere.", en: "Speak with sincerity, words have power." } },
    { id: 6, name: { it: "Bacio", en: "Kiss" }, image: "/src/assets/trinity-tarot-card-06-kiss.jpg", description: { it: "Un segno di affetto e connessione tra le persone.", en: "A sign of affection and connection between people." }, meaning: { it: "Esprime amore, amicizia e intimità.", en: "Expresses love, friendship, and intimacy." }, oracle: { it: "Apriti ai legami autentici.", en: "Open yourself to genuine connections." } },
    { id: 7, name: { it: "Pantera", en: "Panther" }, image: "/src/assets/trinity-tarot-card-07-panther.jpg", description: { it: "Un simbolo di forza e agilità.", en: "A symbol of strength and agility." }, meaning: { it: "Incarna il coraggio e la determinazione.", en: "Embodies courage and determination." }, oracle: { it: "Agisci con sicurezza e potenza.", en: "Act with confidence and power." } },
    { id: 8, name: { it: "Equilibrio", en: "Balance" }, image: "/src/assets/trinity-tarot-card-08-balance.jpg", description: { it: "La necessità di armonizzare le forze opposte.", en: "The need to harmonize opposing forces." }, meaning: { it: "Rappresenta stabilità e pace interiore.", en: "Represents stability and inner peace." }, oracle: { it: "Trova il tuo punto di equilibrio.", en: "Find your point of balance." } },
    { id: 9, name: { it: "Riposo", en: "Rest" }, image: "/src/assets/trinity-tarot-card-09-rest.jpg", description: { it: "Il bisogno di fermarsi per recuperare energia.", en: "The need to stop and regain energy." }, meaning: { it: "Invita alla riflessione e alla rigenerazione.", en: "Encourages reflection and regeneration." }, oracle: { it: "Concediti un momento di pausa.", en: "Allow yourself a moment of pause." } },
    { id: 10, name: { it: "Chiave", en: "Key" }, image: "/src/assets/trinity-tarot-card-10-key.jpg", description: { it: "Uno strumento per aprire nuove opportunità.", en: "A tool to unlock new opportunities." }, meaning: { it: "Rappresenta la soluzione ai problemi.", en: "Represents the solution to problems." }, oracle: { it: "La risposta è più vicina di quanto pensi.", en: "The answer is closer than you think." } },
    { id: 11, name: { it: "Forza", en: "Force" }, image: "/src/assets/trinity-tarot-card-11-force.jpg", description: { it: "Il potere interiore per superare le difficoltà.", en: "The inner power to overcome difficulties." }, meaning: { it: "Simbolo di determinazione e resistenza.", en: "Symbol of determination and resilience." }, oracle: { it: "Abbi fiducia nella tua forza.", en: "Have faith in your strength." } },
    { id: 12, name: { it: "Rivoluzione", en: "Revolution" }, image: "/src/assets/trinity-tarot-card-12-revolution.jpg", description: { it: "Un cambiamento radicale che trasforma tutto.", en: "A radical change that transforms everything." }, meaning: { it: "Segno di trasformazione e rinnovamento.", en: "Sign of transformation and renewal." }, oracle: { it: "Abbraccia il cambiamento con coraggio.", en: "Embrace change with courage." } },
    { id: 13, name: { it: "Sonno", en: "Sleep" }, image: "/src/assets/trinity-tarot-card-13-sleep.jpg", description: { it: "Un momento di riposo necessario per rigenerarsi.", en: "A necessary moment of rest to regenerate." }, meaning: { it: "Indicazione di rilassamento e introspezione.", en: "Sign of relaxation and introspection." }, oracle: { it: "Concediti una pausa per ricaricarti.", en: "Take a break to recharge." } },
    { id: 14, name: { it: "Anima", en: "Soul" }, image: "/src/assets/trinity-tarot-card-14-soul.jpg", description: { it: "La parte più profonda e autentica di noi stessi.", en: "The deepest and most authentic part of ourselves." }, meaning: { it: "Rappresenta la connessione spirituale.", en: "Represents spiritual connection." }, oracle: { it: "Ascolta la tua voce interiore.", en: "Listen to your inner voice." } },
    { id: 15, name: { it: "Significato", en: "Meaning" }, image: "/src/assets/trinity-tarot-card-15-meaning.jpg", description: { it: "La ricerca di un senso in ciò che accade.", en: "The search for meaning in what happens." }, meaning: { it: "Indicazione di riflessione e scoperta.", en: "Sign of reflection and discovery." }, oracle: { it: "Guarda oltre l'apparenza delle cose.", en: "Look beyond appearances." } },
    { id: 16, name: { it: "Ancora", en: "Anchor" }, image: "/src/assets/trinity-tarot-card-16-anchor.jpg", description: { it: "Stabilità e sicurezza, un punto di riferimento.", en: "Stability and security, a point of reference." }, meaning: { it: "Segno di fermezza e radicamento.", en: "Sign of steadiness and grounding." }, oracle: { it: "Affidati alle tue basi solide.", en: "Trust in your solid foundations." } },
    { id: 17, name: { it: "Scale", en: "Stairs" }, image: "/src/assets/trinity-tarot-card-17-stairs.jpg", description: { it: "Un percorso verso la crescita e l'elevazione.", en: "A path towards growth and elevation." }, meaning: { it: "Simbolo di progresso e ascensione.", en: "Symbol of progress and ascension." }, oracle: { it: "Sali un gradino alla volta.", en: "Climb one step at a time." } },
    { id: 18, name: { it: "Cobra", en: "Cobra" }, image: "/src/assets/trinity-tarot-card-18-cobra.jpg", description: { it: "La difesa della conoscenza preziosa.", en: "The defense of precious knowledge." }, meaning: { it: "Segno di protezione e vigilanza.", en: "Sign of protection and vigilance." }, oracle: { it: "Proteggi ciò che è importante.", en: "Protect what matters." } },
    { id: 19, name: { it: "Sole", en: "Sun" }, image: "/src/assets/trinity-tarot-card-19-sun.jpg", description: { it: "L'energia vitale e la chiarezza.", en: "Vital energy and clarity." }, meaning: { it: "Simbolo di illuminazione e forza.", en: "Symbol of enlightenment and strength." }, oracle: { it: "Lascia che la luce ti guidi.", en: "Let the light guide you." } },
    { id: 20, name: { it: "Stella", en: "Star" }, image: "/src/assets/trinity-tarot-card-20-star.jpg", description: { it: "Un faro di speranza e ispirazione.", en: "A beacon of hope and inspiration." }, meaning: { it: "Indicazione di speranza e guida.", en: "Sign of hope and guidance." }, oracle: { it: "Segui la tua stella interiore.", en: "Follow your inner star." } },
    { id: 21, name: { it: "Trinità", en: "Trinity" }, image: "/src/assets/trinity-tarot-card-21-trinity.jpg", description: { it: "L'unità di corpo, mente e spirito.", en: "The unity of body, mind, and spirit." }, meaning: { it: "Simbolo di armonia e integrazione.", en: "Symbol of harmony and integration." }, oracle: { it: "Trova equilibrio tra le tre forze.", en: "Find balance among the three forces." } },
    { id: 22, name: { it: "Scarabeo", en: "Beetle" }, image: "/src/assets/trinity-tarot-card-22-beetle.jpg", description: { it: "Un simbolo di trasformazione e rinnovamento.", en: "A symbol of transformation and renewal." }, meaning: { it: "Rappresenta la rigenerazione e la crescita.", en: "Represents regeneration and growth." }, oracle: { it: "Accogli il cambiamento con fiducia.", en: "Embrace change with confidence." } },
    { id: 23, name: { it: "Onda", en: "Wave" }, image: "/src/assets/trinity-tarot-card-23-wave.jpg", description: { it: "Il movimento costante e l'adattabilità.", en: "Constant movement and adaptability." }, meaning: { it: "Simbolo di flessibilità e cambiamento.", en: "Symbol of flexibility and change." }, oracle: { it: "Lasciati trasportare dal flusso della vita.", en: "Go with the flow of life." } },
    { id: 24, name: { it: "Piedi in preghiera", en: "Praying Feet" }, image: "/src/assets/trinity-tarot-card-24-praying-feet.jpg", description: { it: "Connessione con la terra e la spiritualità.", en: "Connection with earth and spirituality." }, meaning: { it: "Indica devozione e umiltà.", en: "Indicates devotion and humility." }, oracle: { it: "Rimani saldo nelle tue convinzioni.", en: "Stay firm in your beliefs." } },
    { id: 25, name: { it: "Evoluzione", en: "Evolution" }, image: "/src/assets/trinity-tarot-card-25-evolution.jpg", description: { it: "Il progresso attraverso l'esperienza.", en: "Progress through experience." }, meaning: { it: "Simbolo di apprendimento e crescita.", en: "Symbol of learning and growth." }, oracle: { it: "Accogli le lezioni della vita.", en: "Embrace life's lessons." } },
    { id: 26, name: { it: "Horus", en: "Horus" }, image: "/src/assets/trinity-tarot-card-26-horus.jpg", description: { it: "Protezione e visione superiore.", en: "Protection and higher vision." }, meaning: { it: "Simbolo di potere e conoscenza.", en: "Symbol of power and knowledge." }, oracle: { it: "Guarda oltre il visibile.", en: "See beyond the visible." } },
    { id: 27, name: { it: "Libertà", en: "Freedom" }, image: "/src/assets/trinity-tarot-card-27-freedom.jpg", description: { it: "Liberazione dai limiti imposti.", en: "Liberation from imposed limits." }, meaning: { it: "Rappresenta autonomia e autodeterminazione.", en: "Represents autonomy and self-determination." }, oracle: { it: "Segui il tuo percorso senza paura.", en: "Follow your path without fear." } },
    { id: 28, name: { it: "Vita", en: "Life" }, image: "/src/assets/trinity-tarot-card-28-life.jpg", description: { it: "L'energia vitale e il rinnovamento.", en: "Vital energy and renewal." }, meaning: { it: "Indica un nuovo inizio e possibilità infinite.", en: "Indicates a new beginning and infinite possibilities." }, oracle: { it: "Sii aperto alle opportunità della vita.", en: "Be open to life's opportunities." } }
];

export const selectedCards = writable([]);